/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikacia.spustace;

import Aplikacia.dialogy.NovaAplikacia2;
import java.util.HashMap;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import Aplikacia.polozky.ObrazkoveHraciePole;
import Aplikacia.polozky.skola.Manazer;
import javax.swing.JOptionPane;

/**
 * Tato trieda sluzi na spustenie celej hry cez graficke okno.
 */

public class AplikaciaGUI extends javax.swing.JFrame {
    private javax.swing.JFrame hlavnaAplikacia;
    private ObrazkoveHraciePole pole;
    private Manazer manazer;
   
 /**
 * V konstruktore nastavime windowsovsky look.
 */
    
    public AplikaciaGUI() {
        this.initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
        } catch (Exception e) {
            System.out.println("Nepodporovany look and fell");
        }
        
        this.hlavnaAplikacia = this;
        this.pole = null;
        this.manazer = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txpVypisy = new javax.swing.JScrollPane();
        txpNaseVypisy = new javax.swing.JTextPane();
        jbtSkore = new javax.swing.JButton();
        jbtUloz = new javax.swing.JButton();
        mnbHlavneMenu = new javax.swing.JMenuBar();
        mnuProgram = new javax.swing.JMenu();
        mniNovy = new javax.swing.JMenuItem();
        mniKoniec = new javax.swing.JMenuItem();
        mnuMoznosti = new javax.swing.JMenu();
        mniVypisNakladnyPriestor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txpVypisy.setViewportView(txpNaseVypisy);

        jbtSkore.setText("Zobraz skore");
        jbtSkore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSkoreActionPerformed(evt);
            }
        });

        jbtUloz.setText("Uloz");
        jbtUloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUlozActionPerformed(evt);
            }
        });

        mnuProgram.setLabel("Program");

        mniNovy.setLabel("Novy");
        mniNovy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNovyActionPerformed(evt);
            }
        });
        mnuProgram.add(mniNovy);

        mniKoniec.setLabel("Koniec");
        mniKoniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKoniecActionPerformed(evt);
            }
        });
        mnuProgram.add(mniKoniec);

        mnbHlavneMenu.add(mnuProgram);

        mnuMoznosti.setText("Moznosti");
        mnuMoznosti.setEnabled(false);

        mniVypisNakladnyPriestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVypisNakladnyPriestorActionPerformed(evt);
            }
        });
        mnuMoznosti.add(mniVypisNakladnyPriestor);

        mnbHlavneMenu.add(mnuMoznosti);

        setJMenuBar(mnbHlavneMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbtUloz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtSkore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txpVypisy, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtUloz, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtSkore, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txpVypisy, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniKoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKoniecActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniKoniecActionPerformed

 /**
 * Po kniknuti na tlacidlo Novy sa nam spusti nova hra.
 */
    
    private void mniNovyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNovyActionPerformed
        // TODO add your handling code here:
        
        HashMap<String,Object> preberaneUdaje = new HashMap<String,Object>();
        preberaneUdaje.put("stlaceneOK", new Boolean(false));
        
        
        
        NovaAplikacia2 dialog = new NovaAplikacia2(this.hlavnaAplikacia, true, preberaneUdaje);
        dialog.setVisible(true);
        
        if (((Boolean)preberaneUdaje.get("stlaceneOK")).booleanValue() == true ) {
        
        pole = new ObrazkoveHraciePole(((Integer)preberaneUdaje.get("riadok")).intValue(), ((Integer)preberaneUdaje.get("stlpec")).intValue());
            this.manazer = new Manazer();
            this.manazer.spravujObjekt(this.pole);
                                                
        }
        
    }//GEN-LAST:event_mniNovyActionPerformed

    private void mniVypisNakladnyPriestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVypisNakladnyPriestorActionPerformed
        
    }//GEN-LAST:event_mniVypisNakladnyPriestorActionPerformed

 /**
 * Po kliknuti na tlacidlo skore sa nam ukaze skore jednotlivych hracov.
 */
    
    private void jbtSkoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSkoreActionPerformed
        // TODO add your handling code here:
        String vysl = this.pole.toString();
        
        if (this.txpNaseVypisy.getText().equals("")) {
            this.txpNaseVypisy.setText(vysl);
        } else {
            this.txpNaseVypisy.setText(this.txpNaseVypisy.getText() + "\n\n"  + vysl);
        }
    }//GEN-LAST:event_jbtSkoreActionPerformed

 /**
 * Po kliknuti na tlacidlo uloz sa nam ulozi skore hracov.
 */
    
    private void jbtUlozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUlozActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Skore hracov bolo uspesne ulozene!");
        this.pole.serialize();
    }//GEN-LAST:event_jbtUlozActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikaciaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtSkore;
    private javax.swing.JButton jbtUloz;
    private javax.swing.JMenuBar mnbHlavneMenu;
    private javax.swing.JMenuItem mniKoniec;
    private javax.swing.JMenuItem mniNovy;
    private javax.swing.JMenuItem mniVypisNakladnyPriestor;
    private javax.swing.JMenu mnuMoznosti;
    private javax.swing.JMenu mnuProgram;
    private javax.swing.JTextPane txpNaseVypisy;
    private javax.swing.JScrollPane txpVypisy;
    // End of variables declaration//GEN-END:variables
}
